// Maps an APPROVED HypothesisIdea to a new StrategyRegistryEntry — the last
// step before strategies/registry.yaml is touched. See
// .claude/skills/tradingview-strategy-generator/registry-integration.md.
//
// Both functions here are deliberately pure: no `node:fs`, no MCP, no
// import of scripts/lib/load-yaml.js or writeRegistry. That's what makes
// "no write before approval" a structural property of this module rather
// than just a documented rule — the actual disk write only happens when the
// calling skill separately imports `writeRegistry` from
// scripts/research/registry-io.ts (reused, not duplicated here) after a
// human has approved the report these entries came from.

import { upsertStrategy } from "../research/registry-io.js";
import type { StrategyRegistry, StrategyRegistryEntry } from "../schemas/registry.js";
import type { HypothesisIdea } from "../schemas/hypothesis.js";

export interface BuildExperimentalEntryOptions {
  idea: HypothesisIdea;
  reportPath: string;
  date: string;
}

function dedupe(values: string[]): string[] {
  return [...new Set(values)];
}

/** Builds a `status: experimental`, `stage: idea` entry with `pine_script_id`
 * and `metrics` both absent (no Pine code, no backtest yet — see
 * scripts/schemas/registry.ts's superRefine). `parameters.initial_research_parameters`
 * is nested under that explicit key so it's never mistaken for tuned/locked
 * parameter values. */
export function buildExperimentalEntry(opts: BuildExperimentalEntryOptions): StrategyRegistryEntry {
  const { idea, reportPath, date } = opts;

  return {
    id: idea.id,
    name: idea.name,
    status: "experimental",
    stage: "idea",
    symbol_universe: idea.initial_symbols,
    timeframe: idea.timeframe_setup,
    created: date,
    last_updated: date,
    reports: { backtests: [], validations: [], ideas: [reportPath] },
    notes: `Generated by tradingview-strategy-generator on ${date}; not backtested; hypothesis: ${idea.synthesis}`,
    description: idea.synthesis,
    version: idea.version,
    family: idea.family,
    providers_tested: idea.compatible_providers,
    timeframes_supported: dedupe([idea.timeframe_context, idea.timeframe_setup, idea.timeframe_trigger]),
    regimes_supported: idea.target_regimes,
    directions_supported: idea.directions,
    sessions_supported: idea.sessions,
    parameters: { initial_research_parameters: idea.initial_research_parameters },
    limitations: idea.falsifiability.possible_biases,
    risks: idea.falsifiability.cost_sensitivity_risks,
    invalidation_conditions: idea.falsifiability.rejection_conditions,
  };
}

/** Folds N approved entries into a registry via the existing, unmodified
 * `upsertStrategy` — still zero fs access, still pure. The calling skill
 * writes the result to disk itself via `writeRegistry`, after approval. */
export function commitApprovedIdeas(registry: StrategyRegistry, entries: StrategyRegistryEntry[]): StrategyRegistry {
  return entries.reduce((acc, entry) => upsertStrategy(acc, entry), registry);
}
