import type { HypothesisIdea } from "../scripts/schemas/hypothesis.js";

export function makeHypothesisIdea(overrides: Partial<HypothesisIdea> = {}): HypothesisIdea {
  return {
    id: "vol-compression-breakout-1",
    name: "Volatility Compression Breakout",
    family: "volatility_compression_breakout",
    version: "0.1.0",
    synthesis: "Trade the expansion that follows a multi-bar volatility compression, entering on the first close outside a tightened range.",
    market_behavior_exploited: "Volatility mean-reverts: prolonged compression (ATR percentile < 20) is statistically followed by expansion, and the breakout direction is informationally meaningful.",
    economic_or_behavioral_rationale: "Market makers narrow spreads and reduce inventory risk during low-information periods, compressing range; when new information arrives, positioning has to catch up quickly, producing expansion.",
    target_markets: ["FX"],
    initial_symbols: ["FX:EURUSD"],
    compatible_providers: ["FX"],
    timeframe_context: "240",
    timeframe_setup: "60",
    timeframe_trigger: "15",
    target_regimes: ["volatility_compression", "breakout_expansion"],
    excluded_regimes: ["high_volatility_disorder", "illiquid_noisy"],
    sessions: ["london", "new_york"],
    directions: ["long", "short"],
    expected_frequency: "2-4 trades per week per symbol",
    complexity: "low",
    data_requirements: ["OHLCV 15m/1h/4h", "ATR(14)", "Bollinger Band width"],
    volume_dependency: false,
    multi_symbol_dependency: false,
    expected_cost_sensitivity: "medium",
    deterministic_rules: {
      regime_filter: "Bollinger Band width percentile (250-bar lookback) below 20 on the setup timeframe at the close of the trigger bar",
      htf_filter: "ATR(14) on the 240m context timeframe below its own 100-bar median",
      setup: "at least 8 consecutive setup-timeframe bars with BB width below the 20th percentile",
      trigger: "close breaks outside the 20-bar Donchian channel formed during the compression window",
      entry: "market entry on the close of the triggering bar if breakout distance exceeds 0.25x ATR(14)",
      stop_loss: "1.2x ATR(14) beyond the breakout bar's opposite extreme",
      invalidation: "close re-enters the pre-breakout compression range within 3 bars",
      target: "2.5x the initial stop distance, or the prior swing extreme, whichever is closer",
      early_exit: "close back inside the Donchian channel before target or stop is hit",
      time_stop: "close the position if neither stop nor target is hit within 20 setup-timeframe bars",
      unclosed_bar_handling: "all triggers evaluated only on confirmed (closed) bars — no intrabar re-evaluation",
      cooldown: "no new entry on the same symbol for 5 bars after a stopped-out trade",
      pyramiding: "no pyramiding — one open position per symbol per direction",
      direction_long: "breakout above the compression range high",
      direction_short: "breakout below the compression range low",
      session_rules: "only take triggers during London or New York session hours",
      exclusions: "skip triggers within 30 minutes of a scheduled high-impact news event, if known",
      gap_handling: "if the trigger bar gaps beyond 1.5x ATR from the prior close, skip the entry for that occurrence",
      exceptional_volatility_handling: "if ATR(14) more than doubles intraday relative to the prior daily close, suspend new entries for the remainder of the session",
    },
    initial_research_parameters: [
      { name: "bb_width_percentile_threshold", initial_value: 20, search_range: "10-30", rationale: "compression should be a genuine tail event, not merely below-average", overfitting_risk: "medium" },
      { name: "compression_min_bars", initial_value: 8, search_range: "5-15", rationale: "long enough to filter noise, short enough to stay reactive", overfitting_risk: "low" },
      { name: "stop_atr_multiple", initial_value: 1.2, search_range: "0.8-2.0", rationale: "wide enough to survive post-breakout retest, tight enough to keep R:R favorable", overfitting_risk: "medium" },
      { name: "target_r_multiple", initial_value: 2.5, search_range: "1.5-4.0", rationale: "standard trend-following R:R starting point", overfitting_risk: "low" },
    ],
    falsifiability: {
      rejection_conditions: ["expectancy is negative after costs across the full in-sample window", "profit factor stays below 1.0 across at least two full market regimes"],
      needs_more_data_conditions: ["fewer than 200 trades in-sample", "no out-of-sample split available yet"],
      key_assumptions: ["ATR percentile is a reasonable proxy for genuine compression, not just low-volatility drift", "breakout direction carries real informational content rather than being coin-flip noise"],
      possible_biases: ["survivorship bias if the symbol universe is chosen after seeing which pairs already had good breakouts", "look-ahead bias if the percentile lookback window inadvertently uses unconfirmed bars"],
      cost_sensitivity_risks: ["frequent stop-outs during choppy false breakouts could make round-trip costs dominate expectancy"],
      excluded_markets: ["illiquid FX crosses with wide typical spreads"],
      benchmark: "buy-and-hold on the same symbol over the same test window",
      contrary_signals: ["win rate concentrated in a single calendar year", "long and short legs show materially different expectancy"],
    },
    differentiation_notes: "The only existing registry entry (sr-volume-zones) trades support/resistance bounces on a single timeframe with no explicit regime filter; this idea targets a distinct regime transition (compression -> expansion) with an explicit multi-timeframe context filter.",
    ...overrides,
  };
}
